# Generated by Django 3.2.13 on 2024-09-03 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0011_parceiro_casa_papai_noel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parceiro_casa_papai_noel',
            options={'verbose_name_plural': 'Parceiros_Casa_Papai_Noel'},
        ),
        migrations.AlterModelOptions(
            name='programacao',
            options={'verbose_name': 'Programação', 'verbose_name_plural': 'Programações'},
        ),
    ]
