# Generated by Django 3.2.13 on 2024-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0012_auto_20240903_1628'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=64, verbose_name='NomeBanner')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='banners/')),
            ],
        ),
    ]
