# Generated by Django 3.2.13 on 2024-10-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0013_noticia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticia',
            name='autor',
        ),
        migrations.AlterField(
            model_name='noticia',
            name='conteudo',
            field=models.TextField(null=True, verbose_name='Conteúdo'),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagem',
            field=models.ImageField(null=True, upload_to='noticias/%Y/%m/%d/', verbose_name='Imagem'),
        ),
    ]
