# Generated by Django 3.2.13 on 2024-10-09 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0013_banner'),
        ('natal', '0014_auto_20241009_1112'),
    ]

    operations = [
    ]
