# Generated by Django 3.2.13 on 2024-10-09 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0015_merge_0013_banner_0014_auto_20241009_1112'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('subtitulo', models.CharField(max_length=300, verbose_name='Título')),
                ('descricao', models.CharField(max_length=10000, verbose_name='Título')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='sections/')),
                ('section_video', models.CharField(max_length=300, verbose_name='Título')),
            ],
        ),
    ]
