# Generated by Django 3.2.13 on 2024-10-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0018_auto_20241009_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sections',
            name='section_video',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Iframe'),
        ),
    ]
