# Generated by Django 3.2.13 on 2024-10-09 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0019_alter_sections_section_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='banner',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='data',
        ),
        migrations.AddField(
            model_name='evento',
            name='section_image',
            field=models.ImageField(blank=True, null=True, upload_to='eventos/'),
        ),
        migrations.AddField(
            model_name='evento',
            name='section_video',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Iframe'),
        ),
        migrations.AddField(
            model_name='evento',
            name='slug',
            field=models.SlugField(default='default-slug', max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao',
            field=models.CharField(max_length=10000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
