# Generated by Django 3.2.13 on 2024-10-09 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0020_auto_20241009_1510'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atracao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('slug', models.SlugField(default='default-slug', max_length=200, unique=True)),
                ('descricao', models.CharField(max_length=10000, verbose_name='Descrição')),
                ('section_video', models.CharField(blank=True, max_length=300, null=True, verbose_name='Iframe')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='atracoes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Evento',
        ),
    ]
