# Generated by Django 3.2.13 on 2024-10-09 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0021_auto_20241009_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='nome',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome'),
        ),
    ]
