# Generated by Django 3.2.13 on 2024-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0022_atracao_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtracaoImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50, null=True, verbose_name='Nome')),
                ('section_image', models.ImageField(blank=True, null=True, upload_to='atracoes-images/')),
            ],
        ),
    ]
