# Generated by Django 3.2.13 on 2024-10-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0026_auto_20241010_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atracaoimages',
            name='atracaoImage_image',
            field=models.ImageField(blank=True, null=True, upload_to='atracoes-images/'),
        ),
    ]
