# Generated by Django 3.2.13 on 2024-10-10 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0027_alter_atracaoimages_atracaoimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atracao',
            old_name='atracao_image',
            new_name='section_image',
        ),
        migrations.RenameField(
            model_name='atracao',
            old_name='atracao_video',
            new_name='section_video',
        ),
        migrations.RemoveField(
            model_name='atracaoimages',
            name='atracaoImage_image',
        ),
        migrations.AddField(
            model_name='atracaoimages',
            name='section_image',
            field=models.ImageField(default='default-slug', upload_to='atracoes-images/'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='descricao',
            field=models.CharField(max_length=10000, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
    ]
