# Generated by Django 3.2.13 on 2024-10-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0029_alter_atracaoimages_section_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='atracao',
            name='subtitulo',
            field=models.TextField(blank=True, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='atracao',
            name='titulo',
            field=models.TextField(blank=True, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sections',
            name='subtitulo',
            field=models.TextField(blank=True, null=True, verbose_name='Subtítulo'),
        ),
    ]
