# Generated by Django 3.2.13 on 2024-10-10 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0030_auto_20241010_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atracao',
            name='subtitulo',
        ),
    ]
