# Generated by Django 3.2.13 on 2024-11-01 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0032_programacaodata_programacaoeventos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacaoeventos',
            name='hora',
            field=models.CharField(max_length=10),
        ),
    ]
