# Generated by Django 3.2.13 on 2024-11-01 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0033_alter_programacaoeventos_hora'),
    ]

    operations = [
        migrations.RenameField(
            model_name='programacaoeventos',
            old_name='nome',
            new_name='titulo_evento',
        ),
    ]
