# Generated by Django 3.2.13 on 2024-11-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('natal', '0035_programacaoeventos_publicado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programacaoeventos',
            name='hora',
            field=models.TimeField(),
        ),
    ]
